# Change these first
owner: FrancXPT # Your GitHub organization or username, where this repository lives
repo: upptimer # The name of this repository

sites:
  - name: MAIN Server
    check: "tcp-ping"
    url: $MAIN_SERVER
    port: 2222
    icon: https://img.icons8.com/color/deployment
  - name: AFF Server
    check: "tcp-ping"
    url: $AFF_SERVER
    port: 22
    icon: https://media.licdn.com/dms/image/C4D03AQFAUVtfcwQqrg/profile-displayphoto-shrink_800_800/0/1550163828067?e=1700697600&v=beta&t=-7RhjaCtqMD_ADZBM5lv6CYIMpL7W2mzPNHGtMzAmk4
  - name: PROXY Server
    check: "tcp-ping"
    url: $PROXY_SERVER
    port: 22
    icon: https://www.itadvisor.ma/favicon.ico
  - name: TOOLS Server
    check: "tcp-ping"
    url: $TOOLS_SERVER
    port: 22
    icon: https://img.icons8.com/color/maintenance
  - name: WEBPANEL Server
    check: "tcp-ping"
    url: $WEBPANEL_SERVER
    port: 22
    icon: https://img.icons8.com/color/dashboard-layout


status-website:
  # themeUrl: https://status.bbamoula.ml/custom.css
  cname: status.bba-tech.ma
  # baseUrl: /upptimer
  themeUrl: https://status.bba-tech.ma/custom.css
  logoUrl: https://bba-tech.ma/web/image/website/1/favicon
  favicon: https://bba-tech.ma/web/image/website/1/favicon
  name: BBA-TECH Upptimer
  introTitle: "**Upptimer** is an uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page that uses **real-time** data. No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
i18n:
  footer: Powered by ☕ and ⚡ [FrancXPT](https://gh.bba-tech.ma/)
  url: "https://status.bba-tech.ma"
  allSystemsOperational: "🚀 All systems operational"
  degradedPerformance: "🟨 Degraded performance"
  completeOutage: "🟥 Complete outage"
  partialOutage: "🟧 Partial outage"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
